// AUTO-GENERATED by `logos-ts capture components-facttable--complete`.
// Frozen DOM spec for FactTable/Complete.
// The snapshot is the oracle: re-run after editing the story to re-capture.
import { test, expect } from "vitest"
import { render } from "@testing-library/react"
import { composeStories } from "@storybook/react"
import * as stories from "./FactTable.stories"

const { Complete } = composeStories(stories)

test("captured: FactTable/Complete", () => {
  const { container } = render(<Complete />)
  expect(container.innerHTML).toMatchSnapshot()
})
