// AUTO-GENERATED by `logos-ts capture components-facttable--hybrid-pill`.
// Frozen DOM spec for FactTable/HybridPill.
// The snapshot is the oracle: re-run after editing the story to re-capture.
import { test, expect } from "vitest"
import { render } from "@testing-library/react"
import { composeStories } from "@storybook/react"
import * as stories from "./FactTable.stories"

const { HybridPill } = composeStories(stories)

test("captured: FactTable/HybridPill", () => {
  const { container } = render(<HybridPill />)
  expect(container.innerHTML).toMatchSnapshot()
})
