// AUTO-GENERATED by `logos-ts capture directory-jobrow--default`.
// Frozen DOM spec for JobRow/Default.
// The snapshot is the oracle: re-run after editing the story to re-capture.
import { test, expect } from "vitest"
import { render } from "@testing-library/react"
import { composeStories } from "@storybook/react"
import * as stories from "./JobRow.stories"

const { Default } = composeStories(stories)

test("captured: JobRow/Default", () => {
  const { container } = render(<Default />)
  expect(container.innerHTML).toMatchSnapshot()
})
