import { writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { loadProject } from "./project.js"
import { indexStories, type StoryEntry } from "./stories.js"

// The frozen-DOM test we emit for a captured story. It renders the composed
// story (args + decorators applied) and snapshots its DOM as the oracle.
function capturedTestSource(entry: StoryEntry): string {
  return `// AUTO-GENERATED by \`logos-ts capture ${entry.id}\`.
// Frozen DOM spec for ${entry.component}/${entry.exportName}.
// The snapshot is the oracle: re-run after editing the story to re-capture.
import { test, expect } from "vitest"
import { render } from "@testing-library/react"
import { composeStories } from "@storybook/react"
import * as stories from "./${entry.storiesModule}"

const { ${entry.exportName} } = composeStories(stories)

test("captured: ${entry.component}/${entry.exportName}", () => {
  const { container } = render(<${entry.exportName} />)
  expect(container.innerHTML).toMatchSnapshot()
})
`
}

// Save a single story (by storybook id, or by bare export name) as a test.
export function captureStory(root: string, storyRef: string): string {
  const project = loadProject(root)
  const sfs = project.getSourceFiles().filter((s) => !s.getFilePath().includes("/node_modules/"))
  const entries = indexStories(sfs)

  const entry =
    entries.find((e) => e.id === storyRef) ?? entries.find((e) => e.exportName === storyRef)
  if (!entry) {
    const available = entries.map((e) => e.id).join("\n  ")
    throw new Error(`No story "${storyRef}". Available:\n  ${available}`)
  }

  const componentBase = entry.storiesModule.replace(/\.stories$/, "")
  const outPath = join(dirname(entry.filePath), `${componentBase}.${entry.exportName}.captured.test.tsx`)
  writeFileSync(outPath, capturedTestSource(entry))
  return outPath
}

// CLI: tsx src/capture.ts <root> <storyId|exportName>
const [, , root = "../hn-jobs", storyRef] = process.argv
if (!storyRef) {
  console.error("usage: capture <root> <storyId|exportName>")
  process.exit(1)
}
const written = captureStory(root, storyRef)
console.log(`captured -> ${written}`)
